/*
 * Problem Statement:
 * Given a digit string (2-9), return all possible letter combinations based on phone keypad mapping.
 *
 * Intuition:
 * Each digit contributes a choice set. The final answer is the Cartesian product of choices across positions,
 * naturally generated by backtracking.
 *
 * Approach:
 * - Use mapping array where index=digit.
 * - Recurse by position index.
 * - At each level, append each possible letter and recurse to next digit.
 * - When index reaches digits.length(), record one full combination.
 *
 * Time Complexity (with concrete justification):
 * O(4^n * n) in worst case (all digits are 7/9 with 4 letters).
 * There are up to 4^n combinations, and building/storing each string of length n costs O(n).
 *
 * Space Complexity (with concrete justification):
 * O(n) recursion depth (auxiliary stack), excluding output.
 * Output itself is O(4^n * n).
 *
 * Edge Cases handled:
 * - Empty input returns empty list immediately.
 * - Digits with 3 letters and 4 letters handled uniformly by mapping lookup.
 *
 * Dry Run (concrete example with state):
 * digits = "23"
 * index=0, letters="abc"
 * choose 'a' -> index=1, letters="def" -> add "ad","ae","af"
 * choose 'b' -> add "bd","be","bf"
 * choose 'c' -> add "cd","ce","cf"
 *
 * LeetCode matching/assumption:
 * Matches LeetCode 17. Assumes input digits are within [2..9] per constraints.
 *
 * Correctness Check:
 * Base case adds exactly one string per root-to-leaf decision path, so no missing or duplicate combinations
 * for a fixed mapping. If digits included 0/1, mapping here would produce literal "0"/"1", which is outside
 * standard LeetCode 17 assumptions.
 */

import java.util.*;

public class LetterCombinationsofaPhoneNumber17 {
    public List<String> letterCombinations(String digits) {
        List<String> res = new ArrayList<>();
        // No digits means no combinations.
        if (digits.length() == 0)
            return res;
        String[] mapping = new String[] { "0", "1", "abc", "def", "ghi", "jkl", "mno", "pqrs", "tuv", "wxyz" };
        // Start DFS from index 0 with an empty partial combination.
        helper(res, digits, "", 0, mapping);
        return res;
    }

    private void helper(List<String> res, String digits, String current, int index, String[] mapping) {
        // Reached one complete choice per digit; commit this combination.
        if (index == digits.length()) {
            res.add(current);
            return;
        }
        // Fetch candidate letters for the current digit position.
        String letters = mapping[digits.charAt(index) - '0'];
        for (int i = 0; i < letters.length(); i++) {
            // Extend current prefix by one letter and solve for the next digit.
            helper(res, digits, current + letters.charAt(i), index + 1, mapping);
        }
    }
}
